### ISSUE TITLE
Bad hardcoded output path in `metasample.py`

### ISSUE THREAD

**Issue by Feat-FeAR** [TCP-Lab/transportome_profiler#26]
A just-a-little-too-absolute path prevents `metasample` from working on computers other than the developer's.

See `metasample.py` @ line 199:
```py
temp = Path("/home/hedmad/temp_metasample")
```

Can't we use the `/tmp` folder instead? It should be always accessible and writable by everyone...

**Comment by MrHedmad** [comment]
Fixed in 32f40b74b6. FYI the 'invalid' tag is for issues that are not relevant (if you hover over the label the description says "this doesn't seem right"). If something is not working the only label to apply is "bug".

**Comment by Feat-FeAR** [comment]
ohhhh... got it! :-D
I thought "this doesn't seem right" referred to the code and not the comments... sorry!
