### ISSUE TITLE
Redundancy in `dea_queries.json`

### ISSUE THREAD

**Issue by Feat-FeAR** [TCP-Lab/transportome_profiler#28]
In [`dea_queries.json`](https://github.com/TCP-Lab/transportome_profiler/blob/ef2b50da6db387a92c091323587b9c7aa4279612/data/in/dea_queries.json) all _control_ queries end with
```
...&_sample_type=[Normal Tissue,Solid Tissue Normal]&_sample_type!=Cell Line"
```
which is redundant, because if `_sample_type` must be equal to either X or Y, it is unnecessary to say that it must also be different from Z.
I believe that the last part of each control line can be safely removed, but even leaving it in should change nothing... except, perhaps, a few ms of execution time.

**Comment by MrHedmad** [comment]
This is addressed in #30 (commit 5e38721).
