### ISSUE TITLE
Review of the queries for the TCGA-GTEX pairing.

### ISSUE THREAD

**Issue by Feat-FeAR** [TCP-Lab/transportome_profiler#29]
The current matching between TCGA and GTEX studies is questionable for some tissue types. This is my proposal for changing the queries in the `dea_queries.json` file.

1. Two types should be removed since there are no cancer samples from TCGA to be associated.
    1. Remove `Intestinal_cancer` type.
    2. Remove `Salivary_cancer` type.
1. Some types could be "cleaned up", since by losing a relatively small number of samples (indicated in parentheses) it is reasonable to expect greater homogeneity among the remaining tissues.
    1. `_primary_site=[Colon,Rectum]` ==> `_primary_site=[Colon]` **(103/796)**
        *(based on PMID: 26145760, 30200215, 19581844)*
    1. `_primary_site=[Brain,Pituitary]` ==> `_primary_site=[Brain]` **(107/1953)**
    1. `_primary_site=[Bile duct,Liver]` ==> `_primary_site=[Liver]` **(45/576)**
    1. `_primary_site=[Fallopian Tube,Ovary]` ==> `_primary_site=[Ovary]` **(5/520)**
1. The current `Female_ro_cancer` type would be better split into 2 new types, based on their different site of origin
    `_primary_site=[Cervix,Cervix Uteri,Uterus,Endometrium,Vagina]` ==>
    `_primary_site=[Cervix,Cervix Uteri,Vagina]` (new *Cervix* group, *n*=404)
    `_primary_site=[Uterus,Endometrium]` (new *Uterus* group, *n*=339)
1. Finally, I retain many doubts about the validity of the `Lymphoma` type (`_primary_site=[Blood,White blood cell,Bone Marrow]`), also considering that the `Lymphatic tissue` type is currently unused...

**Comment by MrHedmad** [comment]
In #30 I apply many of these fixes. The issues about Lymphoma are still up in the air though.

With the above fix `kerblam run --profile test -l` executes without issues.
