### ISSUE TITLE
Extract ENSG-HGNC ID correspondences from the MTP-DB

### ISSUE THREAD

**Issue by Feat-FeAR** [TCP-Lab/transportome_profiler#39]
The file `./data/in/ensg_data.csv` (used by `run_gsea.R`) is currently fetched from GitHub Gist. Extracting it from the corresponding MTP-DB table would represent a more "consistent" solution.

**Comment by MrHedmad** [comment]
The `run_gsea.R` script uses this data to filter for coding genes only. We have no such information (i.e. whether the gene is coding or non-coding) in the MTP-DB. So the strategy to fetch pre-downloaded data is the best one, for now. A better repo (not gists) might be worthwhile, though.

**Comment by MrHedmad** [comment]
I've moved the data to Zenodo ([here](https://zenodo.org/records/14225008)) and changed the fetch URL to it in [d942e28](https://github.com/TCP-Lab/transportome_profiler/commit/d942e2884c1d02b4590f9b41bf77ab74874f053e).
